<?php
if (!defined('ABSPATH')) exit; // Exit if accessed directly

if (!function_exists('cptui_register_booking_cpta_fields')) {
	function cptui_register_booking_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_621eb09d2ec7e',
				'title' => 'Booking',
				'fields' => array(
					array(
						'key' => 'field_621eb0e90d330',
						'label' => 'Start Date',
						'name' => 'start_date',
						'type' => 'date_picker',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'm/d/Y',
						'return_format' => 'Ymd',
						'first_day' => 1,
					),
					array(
						'key' => 'field_621eb287b16e3',
						'label' => 'End Date',
						'name' => 'end_date',
						'type' => 'date_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'm/d/Y',
						'return_format' => 'Ymd',
						'first_day' => 1,
					),
					array(
						'key' => 'field_621eb2b2b16e4',
						'label' => 'Status',
						'name' => 'status',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'inquiry' => 'Inquiry',
							'tentative' => 'Tentative',
							'booked' => 'Booked',
							'event' => 'Event',
							'holiday' => 'Holiday',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'inquiry',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_621fa0926aa63',
						'label' => 'Comment',
						'name' => 'comment',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'booking',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'page_attributes',
					10 => 'featured_image',
					11 => 'categories',
					12 => 'tags',
					13 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_testimonial_cpta_fields')) {
	function cptui_register_testimonial_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_621e551a87429',
				'title' => 'Testimonial',
				'fields' => array(
					array(
						'key' => 'field_621e5556457dc',
						'label' => 'Picture',
						'name' => 'picture',
						'type' => 'image',
						'instructions' => 'Use an image with a square thumbnail. (Standard: generic avatar image)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 150,
						'min_height' => 150,
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_621e89acd7d46',
						'label' => 'Gender',
						'name' => 'gender',
						'type' => 'radio',
						'instructions' => 'Gender for the generic avatar picture.',
						'required' => 1,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_621e5556457dc',
									'operator' => '==empty',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'male' => 'Male',
							'female' => 'Female',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'Male',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_621e5587457dd',
						'label' => 'Job Title(s)',
						'name' => 'title',
						'type' => 'wysiwyg',
						'instructions' => 'Enter all job titles and credentials.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_621e56b69deab',
						'label' => 'Star Rating',
						'name' => 'stars',
						'type' => 'number',
						'instructions' => 'Enter the number of stars from 1 - 5 with step size 0.5. (Standard: 5)',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 5,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 1,
						'max' => 5,
						'step' => '0.5',
					),
					array(
						'key' => 'field_621e571e9deac',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => 'Enter the testimonial.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'testimonial',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'featured_image',
					10 => 'tags',
					11 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_faq_cpta_fields')) {
	function cptui_register_faq_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_622657270b3d3',
				'title' => 'FAQ',
				'fields' => array(
					array(
						'key' => 'field_622657539f7ca',
						'label' => 'Answer',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_622657719f7cb',
						'label' => 'Icon',
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5ece4797eaf5e',
						'label' => 'Featured Image Position',
						'name' => 'image_position',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'left',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'faq',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_alert_cpta_fields')) {
	function cptui_register_alert_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_62266099aa59a',
				'title' => 'Alerts',
				'fields' => array(
					array(
						'key' => 'field_62266099b0004',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_623206883374b',
						'label' => 'Color',
						'name' => 'color',
						'type' => 'select',
						'instructions' => '<p>You can see the actual colors for your theme here: <a href="' . site_url('theme-demo') . '#buttons"  target="_blank" rel="noreferrer noopener">Theme Demo</a></p>',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'default' => 'Default',
							'primary' => 'Primary',
							'secondary' => 'Secondary',
							'info' => 'Info',
							'success' => 'Success',
							'warning' => 'Warning',
							'danger' => 'Danger',
						),
						'default_value' => 'default',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'alert',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'featured_image',
					10 => 'categories',
					11 => 'tags',
					12 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_news_cpta_fields')) {
	function cptui_register_news_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_62267284167b3',
				'title' => 'News',
				'fields' => array(
					array(
						'key' => 'field_6226728420269',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_622672e07d5f7',
						'label' => 'Icon',
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_626942722e896',
						'label' => 'Featured Image Position',
						'name' => 'image_position',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'left',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'news',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_fundraiser_cpta_fields')) {
	function cptui_register_fundraiser_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_6226765a5f488',
				'title' => 'Fundraiser',
				'fields' => array(
					array(
						'key' => 'field_6226765a6456b',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_6226765a645a4',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_6269669bdd67d',
						'label' => 'Featured Image Position',
						'name' => 'image_position',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'left',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'fundraiser',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_event_cpta_fields')) {
	function cptui_register_event_cpta_fields() {
		if( function_exists('acf_add_local_field_group') ) {
			acf_add_local_field_group(array(
				'key' => 'group_6238e00ed8652',
				'title' => 'Event',
				'fields' => array(
					array(
						'key' => 'field_623a0a203dd13',
						'label' => 'Icon',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Optional thumbnail that will be shown to the left of the event entry.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_6238e0fe5e63f',
						'label' => 'Start Date',
						'name' => 'start_date',
						'type' => 'date_time_picker',
						'instructions' => 'Use "12:00 am" for full day.',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'm/d/Y g:i a',
						'return_format' => 'Y-m-d H:i:s',
						'first_day' => 1,
					),
					array(
						'key' => 'field_6238e1445e640',
						'label' => 'End Date',
						'name' => 'end_date',
						'type' => 'date_time_picker',
						'instructions' => 'Use "12:00 am" for full day.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'm/d/Y g:i a',
						'return_format' => 'Y-m-d H:i:s',
						'first_day' => 1,
					),
					array(
						'key' => 'field_623a09223fbe6',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_626966c1aa700',
						'label' => 'Featured Image Position',
						'name' => 'image_position',
						'type' => 'radio',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'default_value' => 'left',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'event',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'page_attributes',
					10 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}

if (!function_exists('cptui_register_contact_cpta_fields')) {
	function cptui_register_contact_cpta_fields() {
		if(function_exists('acf_add_local_field_group')) {
			acf_add_local_field_group(array(
				'key' => 'group_6269c899d45d2',
				'title' => 'Contacts',
				'fields' => array(
					array(
						'key' => 'field_6269ca8369656',
						'label' => 'Position',
						'name' => 'position',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_6269c90169654',
						'label' => 'Email',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_6269c92169655',
						'label' => 'Phone',
						'name' => 'phone',
						'type' => 'text',
						'instructions' => 'Format phone number for display.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6269cd2b657ac',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_626adde263463',
						'label' => 'Twitter URL',
						'name' => 'twitter_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_626ade0e63464',
						'label' => 'Facebook URL',
						'name' => 'facebook_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_626ade4163465',
						'label' => 'Instagram URL',
						'name' => 'instagram_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_626ade6863466',
						'label' => 'LinkedIn URL',
						'name' => 'linkedin_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'contact',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'seamless',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'discussion',
					4 => 'comments',
					5 => 'revisions',
					6 => 'slug',
					7 => 'author',
					8 => 'format',
					9 => 'send-trackbacks',
				),
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			));
		}
	}
}
